name: Deploy to staging
on:
  push:
    branches: [ "Staging" ]
  pull_request:
    branches: [ "Staging" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name : checkout the repo
      uses: actions/checkout@v4
    - name: Deploy
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service_id: d1ar6115pdvs73d78ec0
        api_key: rnd_fxQthqT8chhQ5rJ83kqj4DKedjjf
        wait-for-success: true