name: Deploy to production
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: checkout the repo
      uses: actions/checkout@v4
    - name: Deploy
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service_id: srv-d1aquqbe5dus73duvsb0
        api_key: rnd_fxQthqT8chhQ5rJ83kqj4DKedjjf
        wait-for-success: true
