name: Deploy to qa
on:
  push:
    branches: [ "QA" ]
  pull_request:
    branches: [ "QA" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout the repo
      uses: actions/checkout@v4
    - name: Deploy
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service_id: d1ar8mbe5dus73dvag10
        api_key: rnd_fxQthqT8chhQ5rJ83kqj4DKedjjf
        wait-for-success: true